- callsign: LFBA_TWR
  color: '#71aa71'
- callsign: LFBB_CTR
  color: '#837285'
- callsign: LFBB_H2_CTR
  color: '#9f66a0'
- callsign: LFBB_H3_CTR
  color: '#947d9a'
- callsign: LFBB_H4_CTR
  color: '#927b75'
- callsign: LFBB_H5_CTR
  color: '#867e95'
- callsign: LFBB_H_CTR
  color: '#8d6b9c'
- callsign: LFBB_L2_CTR
  color: '#7d6579'
- callsign: LFBB_L3_CTR
  color: '#90858f'
- callsign: LFBB_L4_CTR
  color: '#8e5b68'
- callsign: LFBB_L5_CTR
  color: '#9c7b9a'
- callsign: LFBB_L_CTR
  color: '#666878'
- callsign: LFBB_N2_CTR
  color: '#8c8382'
- callsign: LFBB_N3_CTR
  color: '#976d98'
- callsign: LFBB_N4_CTR
  color: '#8e578d'
- callsign: LFBB_N5_CTR
  color: '#729071'
- callsign: LFBB_N_CTR
  color: '#818d90'
- callsign: LFBB_P2_CTR
  color: '#925e73'
- callsign: LFBB_P3_CTR
  color: '#7d80a0'
- callsign: LFBB_P4_CTR
  color: '#8e8e81'
- callsign: LFBB_P_CTR
  color: '#83798e'
- callsign: LFBB_R2_CTR
  color: '#778a6c'
- callsign: LFBB_R3_CTR
  color: '#8066a0'
- callsign: LFBB_R4_CTR
  color: '#9a619d'
- callsign: LFBB_R5_CTR
  color: '#6a8285'
- callsign: LFBB_R_CTR
  color: '#8f866c'
- callsign: LFBB_T2_CTR
  color: '#7d8b73'
- callsign: LFBB_T3_CTR
  color: '#7373a2'
- callsign: LFBB_T4_CTR
  color: '#6b6875'
- callsign: LFBB_T_CTR
  color: '#797292'
- callsign: LFBB_UN_CTR
  color: '#8f6080'
- callsign: LFBB_US_CTR
  color: '#71568a'
- callsign: LFBB_X2_CTR
  color: '#7358a0'
- callsign: LFBB_X3_CTR
  color: '#697aa1'
- callsign: LFBB_X4_CTR
  color: '#6e8f69'
- callsign: LFBB_X5_CTR
  color: '#6f5f98'
- callsign: LFBB_X_CTR
  color: '#746a8a'
- callsign: LFBB_Z2_CTR
  color: '#9a636e'
- callsign: LFBB_Z3_CTR
  color: '#948679'
- callsign: LFBB_Z4_CTR
  color: '#747d83'
- callsign: LFBB_Z5_CTR
  color: '#958c9e'
- callsign: LFBB_Z_CTR
  color: '#97707a'
- callsign: LFBD_APP
  color: '#a24fde'
- callsign: LFBD_E_APP
  color: '#863deb'
- callsign: LFBD_TWR
  color: '#71aa71'
- callsign: LFBE_TWR
  color: '#71aa71'
- callsign: LFBG_TWR
  color: '#71aa71'
- callsign: LFBH_APP
  color: '#a24fde'
- callsign: LFBH_TWR
  color: '#71aa71'
- callsign: LFBI_APP
  color: '#a24fde'
- callsign: LFBI_TWR
  color: '#71aa71'
- callsign: LFBL_APP
  color: '#a24fde'
- callsign: LFBL_TWR
  color: '#71aa71'
- callsign: LFBO_APP
  color: '#a24fde'
- callsign: LFBO_E_APP
  color: '#9738da'
- callsign: LFBO_TWR
  color: '#71aa71'
- callsign: LFBO_W_APP
  color: '#b655de'
- callsign: LFBP_APP
  color: '#a24fde'
- callsign: LFBP_TWR
  color: '#71aa71'
- callsign: LFBT_TWR
  color: '#71aa71'
- callsign: LFBZ_APP
  color: '#a24fde'
- callsign: LFBZ_TWR
  color: '#71aa71'
- callsign: LFCL_TWR
  color: '#71aa71'
- callsign: LFCR_TWR
  color: '#71aa71'
- callsign: LFLX_TWR
  color: '#71aa71'
- callsign: LFMK_TWR
  color: '#71aa71'
- callsign: LFEE_CTR
  color: '#71aa71'
- callsign: LFEE_HE_CTR
  color: '#64c16a'
- callsign: LFEE_HH_CTR
  color: '#8fb48e'
- callsign: LFEE_HN_CTR
  color: '#8bc270'
- callsign: LFEE_HR_CTR
  color: '#629b6a'
- callsign: LFEE_KD_CTR
  color: '#53c386'
- callsign: LFEE_KE_CTR
  color: '#69af8e'
- callsign: LFEE_KF_CTR
  color: '#5c9c67'
- callsign: LFEE_KH_CTR
  color: '#63bc79'
- callsign: LFEE_KN_CTR
  color: '#74a17c'
- callsign: LFEE_KR_CTR
  color: '#7daa5d'
- callsign: LFEE_N_CTR
  color: '#5f978e'
- callsign: LFEE_S_CTR
  color: '#72bf58'
- callsign: LFEE_UB_CTR
  color: '#6bb181'
- callsign: LFEE_UE_CTR
  color: '#658d72'
- callsign: LFEE_UF_CTR
  color: '#70a98b'
- callsign: LFEE_UH_CTR
  color: '#6db777'
- callsign: LFEE_UN_CTR
  color: '#82b963'
- callsign: LFEE_UR_CTR
  color: '#87c565'
- callsign: LFEE_XE_CTR
  color: '#67a27c'
- callsign: LFEE_XH_CTR
  color: '#6db677'
- callsign: LFEE_XR_CTR
  color: '#79c783'
- callsign: LFEE_YB_CTR
  color: '#59aa60'
- callsign: LFGA_TWR
  color: '#71aa71'
- callsign: LFGJ_TWR
  color: '#71aa71'
- callsign: LFJL_APP
  color: '#a24fde'
- callsign: LFJL_TWR
  color: '#71aa71'
- callsign: LFSB_APP
  color: '#a24fde'
- callsign: LFSB_C_APP
  color: '#be55ec'
- callsign: LFSB_TWR
  color: '#71aa71'
- callsign: LFSI_TWR
  color: '#71aa71'
- callsign: LFSO_TWR
  color: '#71aa71'
- callsign: LFST_APP
  color: '#a24fde'
- callsign: LFST_TWR
  color: '#71aa71'
- callsign: LFSX_TWR
  color: '#71aa71'
- callsign: LFAQ_TWR
  color: '#71aa71'
- callsign: LFAT_TWR
  color: '#71aa71'
- callsign: LFFM_CTR
  color: '#43ffff'
- callsign: LFLD_I_TWR
  color: '#709d6a'
- callsign: LFOA_APP
  color: '#a24fde'
- callsign: LFOA_TWR
  color: '#71aa71'
- callsign: LFOB_APP
  color: '#a24fde'
- callsign: LFOB_TWR
  color: '#71aa71'
- callsign: LFOC_TWR
  color: '#71aa71'
- callsign: LFOH_I_TWR
  color: '#7ba362'
- callsign: LFOJ_APP
  color: '#a24fde'
- callsign: LFOJ_TWR
  color: '#71aa71'
- callsign: LFOP_APP
  color: '#a24fde'
- callsign: LFOP_TWR
  color: '#71aa71'
- callsign: LFOT_APP
  color: '#a24fde'
- callsign: LFOT_TWR
  color: '#71aa71'
- callsign: LFPB_TWR
  color: '#71aa71'
- callsign: LFPG_APP
  color: '#a24fde'
- callsign: LFPG_DEP
  color: '#a24fde'
- callsign: LFPG_FS_APP
  color: '#886deb'
- callsign: LFPG_F_APP
  color: '#964cc2'
- callsign: LFPG_S_APP
  color: '#b251d7'
- callsign: LFPG_S_DEP
  color: '#9354f6'
- callsign: LFPG_S_TWR
  color: '#6aa467'
- callsign: LFPG_TWR
  color: '#71aa71'
- callsign: LFPL_TWR
  color: '#71aa71'
- callsign: LFPN_TWR
  color: '#71aa71'
- callsign: LFPO_APP
  color: '#a24fde'
- callsign: LFPO_DEP
  color: '#a24fde'
- callsign: LFPO_F_APP
  color: '#854bdf'
- callsign: LFPO_TWR
  color: '#71aa71'
- callsign: LFPV_APP
  color: '#a24fde'
- callsign: LFPV_TWR
  color: '#71aa71'
- callsign: LFPZ_TWR
  color: '#71aa71'
- callsign: LFQQ_APP
  color: '#a24fde'
- callsign: LFQQ_TWR
  color: '#71aa71'
- callsign: LFQT_TWR
  color: '#71aa71'
- callsign: LFRC_I_TWR
  color: '#5b8c89'
- callsign: LFRG_APP
  color: '#a24fde'
- callsign: LFRG_TWR
  color: '#71aa71'
- callsign: LFRK_TWR
  color: '#71aa71'
- callsign: LFYR_TWR
  color: '#71aa71'
- callsign: PAR_AENB_CTR
  color: '#5d64ab'
- callsign: PAR_AOML_CTR
  color: '#295da6'
- callsign: PAR_AOUS_CTR
  color: '#3269c0'
- callsign: PAR_AO_CTR
  color: '#3655ab'
- callsign: PAR_APTE_CTR
  color: '#4262b4'
- callsign: PAR_AP_CTR
  color: '#364cb4'
- callsign: PAR_ARML_CTR
  color: '#4b74b7'
- callsign: PAR_AR_CTR
  color: '#4e74c4'
- callsign: PAR_CTR
  color: '#4067a9'
- callsign: PAR_DGTJ_CTR
  color: '#2c62b0'
- callsign: PAR_DG_CTR
  color: '#59538f'
- callsign: PAR_DODG_CTR
  color: '#426ec3'
- callsign: PAR_DOGS_CTR
  color: '#4982b6'
- callsign: PAR_FPAE_CTR
  color: '#5c7ac1'
- callsign: PAR_HPKZ_CTR
  color: '#295ac6'
- callsign: PAR_HP_CTR
  color: '#495dba'
- callsign: PAR_LMHJ_CTR
  color: '#2b6fa9'
- callsign: PAR_LMH_CTR
  color: '#5c55b5'
- callsign: PAR_LOW_CTR
  color: '#51579c'
- callsign: PAR_OPKZ_CTR
  color: '#2965a6'
- callsign: PAR_ORGY_CTR
  color: '#5854a9'
- callsign: PAR_OT_CTR
  color: '#3d6fc4'
- callsign: PAR_PU_CTR
  color: '#22818e'
- callsign: PAR_RPAE_CTR
  color: '#4c7cc6'
- callsign: PAR_RPAW_CTR
  color: '#2b67be'
- callsign: PAR_RT_CTR
  color: '#3d57a0'
- callsign: PAR_TB_CTR
  color: '#4c719a'
- callsign: PAR_TE_CTR
  color: '#3c6bbf'
- callsign: PAR_THUZ_CTR
  color: '#2e78a3'
- callsign: PAR_TH_CTR
  color: '#246094'
- callsign: PAR_TL_CTR
  color: '#365fc4'
- callsign: PAR_TML_CTR
  color: '#5467b4'
- callsign: PAR_TM_CTR
  color: '#3582a2'
- callsign: PAR_TNTB_CTR
  color: '#4c6faa'
- callsign: PAR_TN_CTR
  color: '#235b91'
- callsign: PAR_TP_CTR
  color: '#2c84b4'
- callsign: PAR_UJ_CTR
  color: '#2554ab'
- callsign: PAR_UP_CTR
  color: '#5d4da1'
- callsign: PAR_US_CTR
  color: '#585e91'
- callsign: PAR_UT_CTR
  color: '#446e9f'
- callsign: PAR_UZ_CTR
  color: '#3753a8'
- callsign: LFKB_APP
  color: '#a24fde'
- callsign: LFKB_TWR
  color: '#71aa71'
- callsign: LFKC_TWR
  color: '#71aa71'
- callsign: LFKF_TWR
  color: '#71aa71'
- callsign: LFKJ_APP
  color: '#a24fde'
- callsign: LFKJ_TWR
  color: '#71aa71'
- callsign: LFLB_APP
  color: '#a24fde'
- callsign: LFLB_TWR
  color: '#71aa71'
- callsign: LFLC_APP
  color: '#a24fde'
- callsign: LFLC_S_APP
  color: '#be3cc4'
- callsign: LFLC_TWR
  color: '#71aa71'
- callsign: LFLG_TWR
  color: '#71aa71'
- callsign: LFLL_APP
  color: '#a24fde'
- callsign: LFLL_DEP
  color: '#a24fde'
- callsign: LFLL_E_APP
  color: '#896bca'
- callsign: LFLL_TWR
  color: '#71aa71'
- callsign: LFLP_TWR
  color: '#71aa71'
- callsign: LFLS_TWR
  color: '#71aa71'
- callsign: LFLV_I_TWR
  color: '#78bf54'
- callsign: LFLY_TWR
  color: '#71aa71'
- callsign: LFMA_TWR
  color: '#71aa71'
- callsign: LFMD_TWR
  color: '#71aa71'
- callsign: LFMH_TWR
  color: '#71aa71'
- callsign: LFMI_TWR
  color: '#71aa71'
- callsign: LFML_APP
  color: '#a24fde'
- callsign: LFML_S_APP
  color: '#a059ee'
- callsign: LFML_TWR
  color: '#71aa71'
- callsign: LFMM_CTR
  color: '#909967'
- callsign: LFMM_EU_CTR
  color: '#8d8f7e'
- callsign: LFMM_E_CTR
  color: '#ac824b'
- callsign: LFMM_NE_CTR
  color: '#a6a183'
- callsign: LFMM_NU_CTR
  color: '#9e9756'
- callsign: LFMM_N_CTR
  color: '#82827c'
- callsign: LFMM_U_CTR
  color: '#99aa61'
- callsign: LFMN_APP
  color: '#a24fde'
- callsign: LFMN_DEP
  color: '#a24fde'
- callsign: LFMN_E_APP
  color: '#b96ddf'
- callsign: LFMN_F_APP
  color: '#9d4ddc'
- callsign: LFMN_I_APP
  color: '#9b42d7'
- callsign: LFMN_TWR
  color: '#71aa71'
- callsign: LFMO_TWR
  color: '#71aa71'
- callsign: LFMP_TWR
  color: '#71aa71'
- callsign: LFMT_APP
  color: '#a24fde'
- callsign: LFMT_S_APP
  color: '#9c4ce6'
- callsign: LFMT_TWR
  color: '#71aa71'
- callsign: LFMU_TWR
  color: '#71aa71'
- callsign: LFMV_TWR
  color: '#71aa71'
- callsign: LFTH_APP
  color: '#a24fde'
- callsign: LFTH_TWR
  color: '#71aa71'
- callsign: LFTW_TWR
  color: '#71aa71'
- callsign: LFOU_I_TWR
  color: '#5cab61'
- callsign: LFRB_APP
  color: '#a24fde'
- callsign: LFRB_I_APP
  color: '#854ad7'
- callsign: LFRB_TWR
  color: '#71aa71'
- callsign: LFRD_TWR
  color: '#71aa71'
- callsign: LFRH_APP
  color: '#a24fde'
- callsign: LFRH_TWR
  color: '#71aa71'
- callsign: LFRJ_APP
  color: '#a24fde'
- callsign: LFRJ_TWR
  color: '#71aa71'
- callsign: LFRN_APP
  color: '#a24fde'
- callsign: LFRN_C_APP
  color: '#8456f4'
- callsign: LFRN_N_APP
  color: '#b240f1'
- callsign: LFRN_TWR
  color: '#71aa71'
- callsign: LFRQ_TWR
  color: '#71aa71'
- callsign: LFRR_AI_CTR
  color: '#205e94'
- callsign: LFRR_AU_CTR
  color: '#15716a'
- callsign: LFRR_A_CTR
  color: '#005b88'
- callsign: LFRR_CTR
  color: '#165a86'
- callsign: LFRR_E_CTR
  color: '#1c6a76'
- callsign: LFRR_GI_CTR
  color: '#1e6c78'
- callsign: LFRR_GU_CTR
  color: '#254ba2'
- callsign: LFRR_G_CTR
  color: '#2a5692'
- callsign: LFRR_J_CTR
  color: '#003f8e'
- callsign: LFRR_K_CTR
  color: '#005b9f'
- callsign: LFRR_M_CTR
  color: '#2f52a3'
- callsign: LFRR_N_CTR
  color: '#19688f'
- callsign: LFRR_Q_CTR
  color: '#004993'
- callsign: LFRR_S_CTR
  color: '#095e92'
- callsign: LFRR_UE_CTR
  color: '#04598a'
- callsign: LFRR_US_CTR
  color: '#3069a0'
- callsign: LFRR_VK_CTR
  color: '#035b6a'
- callsign: LFRR_V_CTR
  color: '#344380'
- callsign: LFRR_WI_CTR
  color: '#126fa4'
- callsign: LFRR_WU_CTR
  color: '#005192'
- callsign: LFRR_W_CTR
  color: '#0055a1'
- callsign: LFRR_X_CTR
  color: '#003f8d'
- callsign: LFRR_Z_CTR
  color: '#10407a'
- callsign: LFRS_APP
  color: '#a24fde'
- callsign: LFRS_N_APP
  color: '#bd45e8'
- callsign: LFRS_TWR
  color: '#71aa71'
- callsign: LFRZ_TWR
  color: '#71aa71'
- callsign: LFMM_RAE_CTR
  color: '#9b9762'
- callsign: LFMM_RAW_CTR
  color: '#7f9a7b'
- callsign: LFMM_WU_CTR
  color: '#a88b61'
- callsign: LFMM_W_CTR
  color: '#8fa853'
